### ISSUE TITLE
Crash when adding symbols in script

### ISSUE THREAD

**Issue by Cerzs** [TesterTesterov/MAPTool#2]
Hey there.

I want to change the font, but I can't add symbols like katakanas in script to replace them with actual accented characters, the game just crash. 
Example: `ﾒ=ò`

Any help would be appreciated.

**Comment by TesterTesterov** [comment]
Hmm, it's only the Adabana Odd Tales problem, as far as I know.
Actually, I did investigate this matter long ago and had some results. They are, alas, lossed along with game with edited technical part, but I still remember some points of it that could be helpful, albeit vaguely.

You won't be able to add custom symbols in MAP script without doing something...

So in some archive (the same as MAP file) were files, which did something like validation of characters. Or fitting the characters with images? Don't remember. Either way, it's names, if I don't mistaken, had something like "font" in them (and there were different "font" files for different locales).
And by replacing (not adding, the game will crash otherwise) some symbols from it (by HEX-editing) you would be able to use other characters. Alas, the method also had limits (the game did crash after replacing current characters with others and did not crash after replacing with different ones). Also this had to do with "font" file -- range of accepted characters for replace was different (is it really?) in other files.

Maybe there was something else to do, but I don't remember it at all.

I hope this vague recollection will somehow helpful.

**Comment by Cerzs** [comment]
@TesterTesterov Are you talking about this? 
![imagen](https://user-images.githubusercontent.com/44489935/143149481-924aaf7b-8d8f-42d4-af5c-4884fe00d002.png)

I think is not possible, I don't have enough symbols to replace with my characters...

**Comment by TesterTesterov** [comment]
@Cerzs, yes, highly likely that's it. MAP files, if I remember correctly, has symbols list (in HEX) and TXT... Hmm... Some logic about it? Just cannot remember.

"I think is not possible, I don't have enough symbols to replace with my characters..."
+ Well, you may try to add a new symbols to MAP and edit logic (???) in TXT... Maybe you'll have some results.
+ Okay, I shall tell you another method to do this. Still it would be harder, do note.
+ You may take some other game on Silky Engine and port Adabana Odd Tales to it's version. Their scripts are very close (all Silky Engine scripts are very close) with some distinctions. Basically, you need to copy all commands, but create STRING commands (see it in description of the tool and the code of the other Silky Engine Game) and get there strings from the MAP. It would be code refactoring, basically. And then replace files, only necessary for other game to "become Adabana Odd Tales". Not all files, do note, or other game would inherit the problems of Adabana's technical part.

**Comment by TesterTesterov** [comment]
Seems that the problem is out the scope of the tool. You would need to make fixes outside of MAP, as I have written.
